name: Cypress Tests

on:
  workflow_call:

jobs:
  Cypress-Tests:
    runs-on: windows_prod

    steps:
      - name: "Checkout Code ☁️"
        uses: actions/checkout@v4

      - run: npm i
        working-directory: cypressAutomation/CYAN
      
      - name: "Run Cypress tests 🧪 headed"
        working-directory: cypressAutomation/CYAN
        run: npx cypress run --env testtype=api,TAGS=@Mhra_API,CLIENT_SECRET=${{ secrets.CLIENT_SECRET }},CLIENT_ID=${{ secrets.CLIENT_ID }} --spec './cypress/integration/Sample/features/api/*.feature' --headed --browser chrome

      - name: "Generate report"
        if: always()
        working-directory: cypressAutomation/CYAN
        run: npm run posttestBDD

      - name: "Upload HTML report"
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-report
          path: ./cypressAutomation/CYAN/cypress/reports/**
          retention-days: 4
