export const FIELD_TYPES = {
  BUTTON: "button",
  BUTTONS: "buttons",
  CAPTION: "caption",
  CHECKBOX: "checkbox",
  CHECKBOXES: "checkboxes",
  HINT_LABEL: "hintlabel",
  INPUT: "input",
  INSET: "inset",
  LABEL: "label",
  LINK: "link",
  LIST: "list",
  PANEL: "panel",
  PARAGRAPH: "paragraph",
  RADIO: "radio",
  RADIOS: "radios",
  SELECT: "select",
  TABLE: "table",
  TEXT: "text",
  PREV_LINK: "prevLink",
  PARAGRAPH_WITH_LINK: "paragraphWithLink",
  AUTO_COMPLETE: "autoComplete",
  ADD_MORE: "AddMore",
  UNORDERED_LIST: "unorderedList",
  TEXT_AREA: "textArea",
  HINT_TEXT: "hintText",
  DATE_FIELD: "dateField",
} as const;

export const USER_INPUT_FIELD_TYPES = [
  "checkboxes",
  "input",
  "radios",
  "select",
  "autoComplete",
  "textArea",
  "dateField",
  "AddMore"
];
