name: NextJs Pipeline for PERF,PRE-UAT & UAT deployment
on:
  push:
    branches:
       - "release/**"

jobs:
  Read-Approval:
    runs-on: gp-prod-runner-set
    environment: Approval-Gate
    steps:
      - name: "Approval Status"
        run: |
          echo "Approval Completed" 

  Build:
    if: github.event.created
    needs: Read-Approval
    uses: ./.github/workflows/nextjs-app-ci.yml
    with:
      NODE_VERSION: '20.x'
      artifact_destination: 'Github'
      environment: 'UAT'
      app_name: 'rc-nextjs-app'
      src_path: frontend
      config_path: 'env'
      nexus_artifact_group_id: rc-nextjs-uat
      nexus_artifact_id: frontend
    secrets:
      NPM_REGISTRY_PAT: ${{ secrets.NPM_REGISTRY_PAT }}
      AZURE_CREDENTIALS_RC: ${{ secrets.AZURE_CREDENTIALS_RC }}

  SonarQube:
    needs: Build
    uses: ./.github/workflows/nextjs-app-sonarqube-scan.yml
    with:
      app_name: 'rc-nextjs-app'
      artifact_destination: 'Github'
      nexus_artifact_group_id: rc-nextjs-uat
      nexus_artifact_id: frontend
    secrets:
      SonarAccessToken: ${{ secrets.SONAR_TOKEN }}

  OWASP-Scan:
    needs: Build
    uses: ./.github/workflows/nextjs-app-owasp-scan.yml
    with:
      app_name: 'rc-nextjs-app'
      artifact_destination: 'Github'
      nexus_artifact_group_id: rc-nextjs-uat
      nexus_artifact_id: frontend

  PERF:
    needs: SonarQube
    uses: ./.github/workflows/nextjs-app-deploy-app-service.yml
    with: 
      environment: 'PERF'
      AZURE_WEBAPP_NAME: 'ase-rms-perf-uks-02' 
      resource_group: 'rg-mhra-perf-uks-rms'
      src_path: 'frontend/src'
      app_name: 'rc-nextjs-app'
      config_path: 'env'
      artifact_destination: 'Github'
      nexus_artifact_group_id: rc-nextjs-uat
      nexus_artifact_id: frontend
    secrets:
      AZURE_CREDENTIALS_RC: ${{ secrets.AZURE_CREDENTIALS_RC}}
      REPO_READ_PAT: ${{ secrets.REPO_READ_PAT }}


  PRE-UAT:
    needs: SonarQube
    uses: ./.github/workflows/nextjs-app-deploy-app-service.yml
    with: 
      environment: 'PRE-UAT'
      AZURE_WEBAPP_NAME: 'ase-rms-uat01-uks-02' 
      resource_group: 'rg-mhra-uat-uks-rms'
      slot_name_r2: 'preuat'
      src_path: 'frontend/src'
      app_name: 'rc-nextjs-app'
      config_path: 'env'
      artifact_destination: 'Github'
      nexus_artifact_group_id: rc-nextjs-uat
      nexus_artifact_id: frontend
    secrets:
      AZURE_CREDENTIALS_RC: ${{ secrets.AZURE_CREDENTIALS_RC}}
      REPO_READ_PAT: ${{ secrets.REPO_READ_PAT }}

  UAT:
    needs: SonarQube
    uses: ./.github/workflows/nextjs-app-deploy-app-service.yml
    with: 
      environment: 'UAT'
      AZURE_WEBAPP_NAME: 'ase-rms-uat01-uks-02' 
      resource_group: 'rg-mhra-uat-uks-rms'
      src_path: 'frontend/src'
      app_name: 'rc-nextjs-app'
      config_path: 'env'
      artifact_destination: 'Github'
      nexus_artifact_group_id: rc-nextjs-uat
      nexus_artifact_id: frontend
    secrets:
      AZURE_CREDENTIALS_RC: ${{ secrets.AZURE_CREDENTIALS_RC}}
      REPO_READ_PAT: ${{ secrets.REPO_READ_PAT }}

  DAST-PERF:
    needs: PERF
    uses: ./.github/workflows/nextjs-app-DAST.yml
    with:
      APP_URL: ${{ needs.PERF.outputs.appurl }}
      environment: 'PERF'
      artifact_destination: 'Github'
      nexus_artifact_group_id: rc-nextjs
      nexus_artifact_id: frontend

  DAST-PRE-UAT:
    needs: PRE-UAT
    uses: ./.github/workflows/nextjs-app-DAST.yml
    with:
      APP_URL: ${{ needs.PRE-UAT.outputs.appurl }}
      environment: 'PRE-UAT'
      artifact_destination: 'Github'
      nexus_artifact_group_id: rc-nextjs
      nexus_artifact_id: frontend

  DAST-UAT:
    needs: UAT
    uses: ./.github/workflows/nextjs-app-DAST.yml
    with:
      APP_URL: ${{ needs.UAT.outputs.appurl }}
      environment: 'UAT'
      artifact_destination: 'Github'
      nexus_artifact_group_id: rc-nextjs
      nexus_artifact_id: frontend

  # Test-Accessibility-UAT:
  #   needs: UAT
  #   uses: ./.github/workflows/nextjs-app-run-pa11y.yml
  #   with:
  #     environment: 'UAT'
  #     src_path: frontend
  #     artifact_destination: 'Github'
  #     nexus_artifact_group_id: rc-nextjs-uat
  #     nexus_artifact_id: frontend