name: Nextjs Pipeline
on:
  push:
    branches:
      - "feature/**"
      - "fix/**"
      - "hotfix/**"
      - "develop"      
    paths:
      - "frontend/**"
      - "env/dev_config.json"
      - ".github/workflows/next**"

  pull_request:
    branches:
      - "feature/**"
      - "fix/**"
      - "hotfix/**"
      - "develop"
    types:
      - opened
      - reopened
      - synchronize
    paths:
      - "frontend/**"
      - "env/dev_config.json"
      - ".github/workflows/next**"

jobs:
  Build:
    uses: ./.github/workflows/nextjs-app-ci.yml
    with:
      NODE_VERSION: '20.x'
      artifact_destination: 'Github'
      environment: 'Dev'
      app_name: 'rc-nextjs-app'
      src_path: frontend
      config_path: 'env'
      nexus_artifact_group_id: rc-nextjs-dev
      nexus_artifact_id: frontend
    secrets:
      NPM_REGISTRY_PAT: ${{ secrets.NPM_REGISTRY_PAT }}
      AZURE_CREDENTIALS_RC: ${{ secrets.AZURE_CREDENTIALS_RC }}

  SonarQube:
    if: ${{ (github.event_name == 'pull_request' && ( startsWith(github.head_ref, 'feature/') || startsWith(github.head_ref, 'fix/') || startsWith(github.head_ref, 'hotfix/') )) || github.ref == 'refs/heads/develop' }}
    needs: Build
    uses: ./.github/workflows/nextjs-app-sonarqube-scan.yml
    with:
      app_name: 'rc-nextjs-app'
      artifact_destination: 'Github'
      nexus_artifact_group_id: rc-nextjs-dev
      nexus_artifact_id: frontend
    secrets:
      SonarAccessToken: ${{ secrets.SONAR_TOKEN }}

  OWASP-Scan:
    if: ${{ (github.event_name == 'pull_request' && ( startsWith(github.head_ref, 'feature/') || startsWith(github.head_ref, 'fix/') || startsWith(github.head_ref, 'hotfix/') )) || github.ref == 'refs/heads/develop' }}
    needs: Build
    uses: ./.github/workflows/nextjs-app-owasp-scan.yml
    with:
      app_name: 'rc-nextjs-app'
      artifact_destination: 'Github'
      nexus_artifact_group_id: rc-nextjs-dev
      nexus_artifact_id: frontend

  Dev:
    if: ${{ (github.event_name == 'pull_request' && ( startsWith(github.head_ref, 'feature/') || startsWith(github.head_ref, 'fix/') || startsWith(github.head_ref, 'hotfix/') )) || github.ref == 'refs/heads/develop' }}
    needs: SonarQube
    uses: ./.github/workflows/nextjs-app-deploy-app-service.yml
    with: 
      environment: 'Dev'
      AZURE_WEBAPP_NAME: 'ase-rms-dev01-uks-02' 
      resource_group: 'rg-mhra-dev-uks-rms'
      keyvault_name: 'kvrms02devuks'
      src_path: 'frontend/src'
      app_name: 'rc-nextjs-app'
      config_path: 'env'
      artifact_destination: 'Github'
      nexus_artifact_group_id: rc-nextjs-dev
      nexus_artifact_id: frontend
    secrets:
      AZURE_CREDENTIALS_RC: ${{ secrets.AZURE_CREDENTIALS_RC }}
      REPO_READ_PAT: ${{ secrets.REPO_READ_PAT }}
      SUB_ID: ${{ secrets.SUB_ID }}
      AZURE_CREDENTIALS_B2C_CLIENT_ID: ${{ secrets.AZURE_CREDENTIALS_B2C_CLIENT_ID }}
      AZURE_CREDENTIALS_B2C_CLIENT_SECRET: ${{ secrets.AZURE_CREDENTIALS_B2C_CLIENT_SECRET }}
      AZURE_CREDENTIALS_B2C_TENANT: ${{ secrets.AZURE_CREDENTIALS_B2C_TENANT }}

  Restart-WebApp:
    runs-on: gp-prod-runner-set
    if: ${{ (github.event_name == 'pull_request' && ( startsWith(github.head_ref, 'feature/') || startsWith(github.head_ref, 'fix/') || startsWith(github.head_ref, 'hotfix/') )) }}
    needs: Dev
    environment:
      name: Dev
    env:
      AZURE_WEBAPP_NAME: 'ase-rms-dev01-uks-02' 
      resource_group: 'rg-mhra-dev-uks-rms'
      slotname: ${{ needs.Dev.outputs.slotname }}
    steps:
      - name: "Cleaning up Workspace"
        working-directory: ${{ github.workspace }}
        run: |
          echo "Cleaning up previous run"
          rm -rf *
          ls -al '${{ github.workspace }}'

      - name: "Log in with Azure 🆔"
        uses: azure/login@v2
        with:
          creds: "${{ secrets.AZURE_CREDENTIALS_RC }}"
      
      - name: "Restart application"
        run: |
          az webapp restart --name ${{ env.AZURE_WEBAPP_NAME }} --resource-group ${{ env.resource_group }} --slot ${{ env.slotname }}
          # az webapp stop --name ${{ env.AZURE_WEBAPP_NAME }} --resource-group ${{ env.resource_group }} --slot ${{ env.slotname }}
          # az webapp start --name ${{ env.AZURE_WEBAPP_NAME }} --resource-group ${{ env.resource_group }} --slot ${{ env.slotname }}

  DAST-Feature:
    if: startsWith( github.head_ref, 'feature/' ) || startsWith(github.head_ref, 'fix/') || startsWith(github.head_ref, 'hotfix/')
    needs: Dev
    uses: ./.github/workflows/nextjs-app-DAST.yml
    with:
      APP_URL: ${{ needs.Dev.outputs.appurl }}
      environment: 'Dev'
      artifact_destination: 'Github'
      nexus_artifact_group_id: rc-nextjs
      nexus_artifact_id: frontend

  DAST-Dev:
    if: ${{ github.ref == 'refs/heads/develop' }}
    needs: Dev
    uses: ./.github/workflows/nextjs-app-DAST.yml
    with:
      APP_URL: ${{ needs.Dev.outputs.appurl }}
      environment: 'Dev'
      artifact_destination: 'Github'
      nexus_artifact_group_id: rc-nextjs
      nexus_artifact_id: frontend

  # Test-Accessibility-Dev:
  #   needs: Dev
  #   uses: ./.github/workflows/nextjs-app-run-pa11y.yml
  #   with:
  #     environment: 'Dev'
  #     src_path: frontend
  #     artifact_destination: 'Github'
  #     nexus_artifact_group_id: rc-nextjs-dev
  #     nexus_artifact_id: frontend
